site_name: Boilerplate Laravel 12
site_url: https://marcovegar.github.io/boilerplate-laravel12
repo_url: https://github.com/MarcoVegaR/boilerplate-laravel12
repo_name: MarcoVegaR/boilerplate-laravel12

strict: true

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - i18n:
      languages:
        - locale: es
          name: Español
          default: true
          build: true
  - redirects:
      redirect_maps:
        permissions.md: how-to/permisos-permission-first.md
        auditing-logging.md: explanations/auditoria-vs-logging.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Inicio: index.md
  - Tutoriales:
      - Onboarding: tutorials/onboarding.md
  - Cómo hacer:
      - Permisos (permission-first): how-to/permisos-permission-first.md
      - Registro de usuarios deshabilitado (admin-only): how-to/registro-usuarios-deshabilitado.md
      - Autoeliminación de cuenta deshabilitada: how-to/autoeliminacion-cuenta-deshabilitada.md
      - DataTable Meta-Driven Columns: how-to/datatable-meta-driven-columns.md
  - Backend:
      - Repositories: backend/repositories.md
      - Services: backend/services.md
      - Controllers: backend/controllers.md
      - Flash & Error Handling: backend/flash-and-errors.md
      - Error Pages (Inertia): backend/errors.md
      - Rate Limiting: backend/rate-limiting.md
      - Logging & Context: backend/logging-context.md
      - Policies: backend/policies.md
      - Testing:
          - Repositories: backend/testing-repositories.md
          - Services: backend/testing-services.md
      - Requests:
          - BaseIndexRequest: backend/requests.md
  - Referencia:
      - Variables y permisos: reference/variables-y-permisos.md
      - Localización por defecto (ES): reference/localizacion-por-defecto.md
      - DataTable API: reference/datatable-api.md
      - Gestión de Roles: reference/roles-management.md
  - Explicaciones:
      - Auditoría vs logging: explanations/auditoria-vs-logging.md
  - CI/CD:
      - CI/CD y chequeos locales: ci-cd.md
